---
- hosts: all
  become: yes
  tasks:

    - name: "apt-get update"
      apt:
          update_cache: yes
          cache_valid_time: 3600

    - name: "install nginx"
      apt:
        name: ['nginx']
        state: latest

    - name: "create www directory"
      file:
        path: /var/www/{{ domain }}
        state: directory
        mode: '0775'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
        notify: restart nginx

    - name: copy nginx site.conf
      template:
        src: files/nginx.conf
        dest: /etc/nginx/sites-enabled/{{ domain }}
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Upload default index.html for host
      copy: 
        src: files/static_website/index.html 
        dest: /usr/share/nginx/html/ 
        mode: 0644

    - name: Upload default jpeg for host
      copy: 
        src: files/static_website/sample.jpeg
        dest: /usr/share/nginx/html/ 
        mode: 0644

    - name: Add a line in /etc/nginx/sites-available/default
      lineinfile: 
        dest: /etc/nginx/sites-available/default
                  regexp='# Only for nginx-naxsi'
                  line='location /images {}'   
                      
    - name: Create a directory called images
      file: 
        path: /usr/share/nginx/html/images 
        state: directory 
        mode: 0755

    - name: Upload first image
      copy: 
        src: files/static_website/sample.jpeg 
        dest: /usr/share/nginx/html/images/ 
        mode: 0644
        
    - name: restart nginx
      service:
        name: nginx
        state: restarted